### ISSUE TITLE
Low brightness when setting colors on HomeKit

### ISSUE THREAD

**Issue by fecabianchi** [vieira/homebridge-yeelight-wifi#37] opened 2019-06-28 02:21 UTC
Hi,

If I set the color and brightness (100%) in the Yeelight app, the bulbs look much brighter than if I do the same process on HomeKit. Is this an expected behavior?

Thanks!

**Comment by marcosh72** [comment] 2019-06-30 23:45
I'm experiencing the same situation here. 

It seems like we can't properly enable temperature mode for the color bulbs. In `platform.js:120` we can see that color temperature mode will only be enabled if the bulb doesn't support HSV mode. That means that even though we're able to use the "Temperature" wheel on the iPhone, it will only issue `set_hsv` commands to the bulb, instead of the `set_ct_abx` commands that drive the bulb full brightness.

I wasn't able to find a workaround so far. I tried to enable temperature mode manually but then I could no longer use HSV mode.

More info here: https://github.com/vieira/homebridge-yeelight-wifi/issues/22#issuecomment-452733852

**Comment by vieira** [comment] 2019-07-10 11:10
Hello,

Yes, that is correct as far as I understand it.

The only workaround I know is to tell the plugin to treat a color bulb like a white one with:

```
        "defaultValue": {
            "aed78s": {
                "name": "Kitchen",
                "blacklist": ["set_hsv"]
            }
        }
```

In this scenario we will always use `set_ct_abx` as Homekit will start sending color temperature commands instead of color commands.

Of course the proper fix lies in Yeelight's hands, they specifically broke the brightness in color mode with a firmware update. Before that, both color mode and temperature mode used to have the same max brightness. Although there were various complaints on their forums, facebook and twitter, they never fixed it. In the firmware update released a couple of weeks ago not only is this problem still present but now also the transitions are broken. Really disappointing.

**Comment by okonet** [comment] 2019-12-20 12:23
Duplicate of #22

**Closed as completed by okonet** 2019-12-20 12:23 UTC
